### ISSUE TITLE
add proxy support

### ISSUE THREAD

**Issue by kam1kaze** [sensu-plugins/sensu-plugins-pagerduty#4]
Hi,

We need a proxy support of this plugin. Unfortunately, It looks like we cannot implement such feature until portertech/redphone#9 pull request is merged to redphone library.

**Comment by analytically** [comment]
We're not using redphone anymore.

**Comment by masteinhauser** [comment]
It looks like HTTP Proxy support [is not supported within the pagerduty gem](https://github.com/envato/pagerduty/blob/master/lib/pagerduty/http_transport.rb#L18-L31) when comparing to the Ruby Docs for [`Net::HTTP` and how to use Proxies](http://ruby-doc.org/stdlib-1.9.3/libdoc/net/http/rdoc/Net.html#label-Proxies).

I might be able to provide a PR for this, but we are evaluating using [flapjack.io](flapjack.io) instead of hitting PagerDuty's API directly anyway.

**Comment by orien** [comment]
FYI the Pagerduty gem now has an explicit API for configuring an HTTP proxy. Version 2.1.0 has been released with this feature.

https://github.com/envato/pagerduty/pull/47

**Comment by willejs** [comment]
I was using this plugin with the http/s proxy environment variables defined and im 99.9% sure it worked?

**Comment by masteinhauser** [comment]
@willejs I don't remember exactly what lead me to my conclusion, but it also highly depends on which version of Ruby you are running sensu and the handler under.

**Comment by willejs** [comment]
Ive got the code somewhere where i did this, I remember playing around with this for a while. Essentially, you need to make sure the proxy_server variables are set in the parent process that spawns ruby.
Let me double check.

**Comment by eheydrick** [comment]
Proxy support was added in #26 by @lcrisci and released in version 2.0.0 which is now on Rubygems.
